CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(250)                            NOT NULL,
    requester_id BIGINT                                  NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE default CURRENT_TIMESTAMP,
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT fk_user_id_requester FOREIGN KEY (requester_id) REFERENCES users
);
CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100)                            NOT NULL,
    description VARCHAR(250)                            NOT NULL,
    available   BOOLEAN                                 NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    request_id  BIGINT,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users,
    CONSTRAINT fk_request_id FOREIGN KEY (request_id) REFERENCES requests
);
CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id    BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_time   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status     VARCHAR(30)                             NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT fk_user_booking FOREIGN KEY (user_id) REFERENCES users,
    CONSTRAINT fk_item_booking FOREIGN KEY (item_id) REFERENCES items
);
CREATE TABLE IF NOT EXISTS comments
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text    VARCHAR(250)                            NOT NULL,
    item_id BIGINT                                  NOT NULL,
    user_id BIGINT                                  NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE DEFAULT current_timestamp,
    CONSTRAINT pk_comment PRIMARY KEY (id),
    CONSTRAINT fk_user_id_author FOREIGN KEY (user_id) REFERENCES users,
    CONSTRAINT fk_item_id_comment FOREIGN KEY (item_id) REFERENCES items
);

